### ISSUE TITLE
Entity DataService Configuration

### ISSUE THREAD

**Issue by bellizio** [johnpapa/angular-ngrx-data#122]
Is there an example of how to properly configure the Entity DataService? (root url, etc.) 

I've explored the quickstart app and read through the documentation about the [DefaultDataService](https://github.com/johnpapa/angular-ngrx-data/blob/master/docs/entity-dataservice.md#the-defaultdataservice), but it is still not clear to me as to how to configure it in an application using ngrx-data.

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
> ---------------------------------------------------------------
Excellent work on this library by the way. After struggling to remember the pattern(s) of ngrx by itself, this is a breath of fresh air. Thank you!

**Comment by johnpapa** [comment]
Hi @bellizio ... thank you so much for trying our library and providing this feedback. We are working on more docs, but perhaps I can help get you unstuck in the meantime.

Can you clarify which specific settings you would like to override the configuration for?

**Comment by bellizio** [comment]
@johnpapa thank you for the update!
 
After searching around a little further in the repo, I found what I was looking for here:
https://github.com/johnpapa/angular-ngrx-data/blob/master/src/client/app/store/entity-store.module.ts#L9

**Comment by klauvi** [comment]
Thank you @bellizio, I was having the same exact problem with this configuration. Having a few lines on where and how to apply the default configuration in the documentation would be very helpful.

**Comment by wardbell** [comment]
Ah ... you mean the `DefaultDataServiceConfig`.  We should doc that better and the new `HttpResourceUrls` option.

**Comment by aboudard** [comment]
Hello guys, I don't know how my question fits in this issue, but I'm looking for the way to configure the root /api route. I found the DefaultDataServiceConfig class that seems to do the job but have no clue for now on how to use it in the app.
Thanks :)

**Comment by klauvi** [comment]
If you click the [link](https://github.com/johnpapa/angular-ngrx-data/blob/master/src/client/app/store/entity-store.module.ts#L9) in the comment from @bellizio you can see following.

Create config object:
```
const defaultDataServiceConfig: DefaultDataServiceConfig = {
  root: 'api', // default root path to the server's web api
}
```

Provide it in the NgModule:
```
@NgModule({
  providers: [{ provide: DefaultDataServiceConfig, useValue: defaultDataServiceConfig }]
})
```

**Comment by aboudard** [comment]
oh yes indeed @klauvi , I didn't read correctly the link !
i'll inject the configuration like that :)

**Comment by wardbell** [comment]
I'm closing this issue as it seems to be "solved", except for documentation which is an overall weakness to be corrected elsewhere.

**Comment by kichnan** [comment]
Yeah, some more documentation would be great. One other suggestion: would be much clearer if the `ngrx-data-lab` repository is retired or, at least, the "Quick Start" link be pointing to somewhere in the `app` in this repository.

**Feedback:** When I was going through `ngrx` whether to use it for my app in production and had the exact same thought about the amount of boilerplate code. I had an epiphany that I will write a wrapper over it that will suite my needs. Unfortunately and fortunately, I read about `ngrx-data` in Ngrx's blog announcements. Obviously, this is a MUCH better wrapper!! I tried it out in my app and it works like a charm, almost out of the box (once the configuration values are set, after digging into the documentation files and referring to sample code).

Great work @johnpapa @wardbell ! Would love to contribute to it as well if there is a need.
