### ISSUE TITLE
Feature request: Relative entityHttpResourceUrls

### ISSUE THREAD

**Issue by ogix** [johnpapa/angular-ngrx-data#127]
### This issue is for a: (mark with an `x`)
```
- [] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Versions
> 1.0.0-beta.2

First of all thanks for a great lib! It really helps reducing all the boilerplate.
I have noticed that the `root` config is not respected if you specify `entityHttpResourceUrls` for an entity. 
I would like to specify root url e.g. `https://www.backend.com` and then specify relative `entityHttpResourceUrls` e.g. `api/user`.
Now I have to specify full url which is not very convenient.

**Comment by wardbell** [comment]
Please propose the exact API and rules that you'd like to see. Perhaps a PR would clarify?

**Comment by wardbell** [comment]
Closing as this issue is old and I haven't heard from you.
