### ISSUE TITLE
Is there a way to check if an entity is in the cache?

### ISSUE THREAD

**Issue by RobCannon** [johnpapa/angular-ngrx-data#131]
I would like to check to see if an entity is in the cache before calling service.getByKey().

The only way I have found so far is to subscribe to the keys$ observable and store a copy of the keys so I can check later.  I have to be sure to unsubscribe to that subscription in ngOnDestroy.  

```
this.keySubscription = this.service.keys$.subscribe(keys => {
  this.keys = <string[]>keys;
});
...
if (!this.keys.includes(id)) {
  this.service.getByKey(id);
}
```

I would like to see something along the lines of:
```
if (!this.service.keys.includes(id)) {
  this.service.getByKey(id);
}
```
Or maybe a function to check the key if you want to shield direct access to the keys collection.

**Comment by wardbell** [comment]
I won't get into the reactive style. Instead I'll adjust my answer to fit your thinking.

You don't have to unsubscribe if you know you only want to check the id once. This will do it, using RxJS `first()` or `take(1)` to ensure the observable terminates and unsubscribes after getting the keys:
```
this.service.keys.pipe(first()).subscribe(
  keys => {
    if (!keys.includes(id)) { 
      this.service.getByKey(id);
    }
  }
);
```
It might be faster to check the map
```
this.service.entityMap$.pipe(first()).subscribe(
  map => {
    entity = map[id]; // now you have it if in cache
    if (entity == null) { 
      this.service.getByKey(id);
    }
  }
);
```
I am closing this issue as I don't believe any action is appropriate at this time.
