### ISSUE TITLE
Replacing Pluralizer breaks AOT

### ISSUE THREAD

**Issue by bchiatt** [johnpapa/angular-ngrx-data#135]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
*Automatic Method:*
```
git clone https://github.com/bchiatt/ngrx-data-aot-repro.git && cd ngrx-data-aot-repro && npm install && ng serve --aot
```

*Manual Method:*

Generate new Angular CLI app.

Replace `src/app/app.module.ts` with the following minimal setup:
```
import { BrowserModule } from '@angular/platform-browser';
import { Injectable, NgModule } from '@angular/core';


import { AppComponent } from './app.component';
import { StoreModule } from '@ngrx/store';
import { EffectsModule } from '@ngrx/effects';
import { NgrxDataModule, Pluralizer } from 'ngrx-data';
import { HttpClientModule } from '@angular/common/http';


@Injectable()
export class NoopPluralizer implements Pluralizer {
  pluralize(name: string) {
    return name;
  }
}

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    HttpClientModule,
    StoreModule.forRoot({}),
    EffectsModule.forRoot([]),
    NgrxDataModule.forRoot({})
  ],
  providers: [
    { provide: Pluralizer, useValue: NoopPluralizer }, // <-- Remove this line and AOT works
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
Serve app with AOT flag: `ng serve --aot`

### Any log messages given by the failure
```
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'ngrx-data/utils/index' in '/Users/.../ngrx-data-aot-repro/src/app'
```

### Expected/desired behavior
AOT works when replacing Pluralizer.

### OS and Version?
> macOS High Sierra

### Versions
> 1.0.0-beta.9

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wardbell** [comment]
I encountered this myself. Fixing it.

**Comment by wardbell** [comment]
It's a bug in AOT that I hope to repro and report soon. 
Worked around it in Beta 12, PR #144

**Comment by wardbell** [comment]
OH NO!  The cure was worse than the disease. The problem moved to a different, more important feature. See #145.  

For now, only dev builds work. Trying to solve.

**Comment by wardbell** [comment]
My solution, now in the Beta 13 release, was to remove all barrels in the library. This works everywhere I've tried it.
