### ISSUE TITLE
Demo works great, but reproducing in fresh CLI project throws a ERROR Error: StaticInjectorError(AppModule)[HeroService -> EntityServiceFactory]: 

### ISSUE THREAD

**Issue by SteveStrongBAH** [johnpapa/angular-ngrx-data#137]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I have a repo I can share, but I just created 
ng new ngrx-data-sample

then ran the npm install commands 

npm i @ngrx/effects @ngrx/entity @ngrx/store @ngrx/store-devtools ngrx-data --save

build the components

ng g m store/app-store --flat -m app
ng g m store/entity-store --flat -m store/app-store

Build the app and fixed some references,  but I somehow it is not referencing **EntityServiceFactory**,  I have walked through your example 3 time and I cannot see where I missed this reference.   I should not need to provide it right? It gets provided through the use of ngRx-data right?

### Any log messages given by the failure
>

AppComponent.html:8 ERROR Error: StaticInjectorError(AppModule)[HeroService -> EntityServiceFactory]: 
  StaticInjectorError(Platform: core)[HeroService -> EntityServiceFactory]: 
    NullInjectorError: No provider for EntityServiceFactory!
    at _NullInjector.get (core.js:1003)
    at resolveToken (core.js:1301)
    at tryResolveToken (core.js:1243)
    at StaticInjector.get (core.js:1111)
    at resolveToken (core.js:1301)
    at tryResolveToken (core.js:1243)
    at StaticInjector.get (core.js:1111)
    at resolveNgModuleDep (core.js:10896)
    at _createClass (core.js:10933)
    at _createProviderInstance$1 (core.js:10907)
View_AppComponent_0 @ AppComponent.html:8
AppComponent.html:8 ERROR CONTEXT DebugContext_
View_AppComponent_0 @ AppComponent.html:8
main.ts:12 Error: StaticInjectorError(AppModule)[HeroService -> EntityServiceFactory]: 
  StaticInjectorError(Platform: core)[HeroService -> EntityServiceFactory]: 
    NullInjectorError: No provider for EntityServiceFactory!
    at _NullInjector.get (core.js:1003)
    at resolveToken (core.js:1301)
    at tryResolveToken (core.js:1243)
    at StaticInjector.get (core.js:1111)
    at resolveToken (core.js:1301)
    at tryResolveToken (core.js:1243)
    at StaticInjector.get (core.js:1111)
    at resolveNgModuleDep (core.js:10896)
    at _createClass (core.js:10933)
    at _createProviderInstance$1 (core.js:10907)
### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

windows 10,  Angular 5, VS-Code 
### Versions
>

### Mention any other details that might be useful

Here is the repo.
https://github.com/SteveStrongBAH/ngrx-sample-steve

It is probably something silly,  but I would like a quick look.  I suspect others may run into the same problem when doing something other than the demo.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pfeigl** [comment]
You haven't imported your EntityStoreModule in any module.

**Comment by wardbell** [comment]
What @pfeigl said. You imported the `EntityStoreModule` but neglected to import it from your `AppStoreModule`.

```
@NgModule({
  imports: [
    StoreModule.forRoot({}),
    EffectsModule.forRoot([]),
    // <--- EntityStoreModule goes here
    environment.production ? [] : StoreDevtoolsModule.instrument()
  ]
})
export class AppStoreModule {}
```

Closing.
