### ISSUE TITLE
Pretty cool lib, but, is it possible to use with Angularfire2?

### ISSUE THREAD

**Issue by jaimeyavila** [johnpapa/angular-ngrx-data#140]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

Pretty cool lib, but, is it possible to use with Angularfire2?

**Comment by kjvelarde** [comment]
have you try it?

**Comment by wardbell** [comment]
This would be a good thing for the community to contribute.

My suspicion is that you'll come up with a plug-in substitute for the `DefaultDataServiceFactory`.

I'm closing because the maintainers of this repo aren't going to take this on.
