### ISSUE TITLE
Do you have migration guidance (ngrx infrastructure -> ngrx-data)?

### ISSUE THREAD

**Issue by vetik32** [johnpapa/angular-ngrx-data#142]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
Hello, 
Would you be so kind and let me know if you have migration guidance 
from a project with classic ngrx infrastructure towards this awesome library of yours.
Do they coexist? - or I need 2 different "sandboxes"

Thank you!
p.s. this library is something I was waiting for since I've added 3rd model to our project :)

**Comment by wardbell** [comment]
Sorry I don't and I probably won't get to it. I'm too busy using it. :)

But it you want to write one I'd be happy to reference it.
