### ISSUE TITLE
How to properly map entities before they're saved to the store? [added possible solution]

### ISSUE THREAD

**Issue by sstorie** [johnpapa/angular-ngrx-data#143]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

I am trying to understand how to apply `map` to entities before they're saved to the store when using this library. I don't know if I'm getting a bit lost in the abstractions, or just having a mental block, but what's the easiest way to transform an entity after it's returned from an API, but before it's saved. I just can't see the right extension point yet.

My specific use case is I have a .NET API that's serializing dates to strings, and I'd like to convert them back to proper javascript dates before my app gets access to them. 

_I could create a custom selector to apply this transformation right, but I'd prefer to have the store contain the right types rather than mapping them every time they're requested in the app._

### Any log messages given by the failure

n/a

### Expected/desired behavior

If I'm not already missing it, a quick example in the docs would be helpful here. I'd be happy to write a PR for this once I understand it if you'd find that helpful.

### OS and Version?

Windows 10

### Versions

    "ngrx-data": "^1.0.0-beta.11"

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by sstorie** [comment]
Ok, I think I have a better understanding of this now, and I'd be happy to contribute to the docs if that'd be helpful. Here's a working stackblitz with my modifications: https://stackblitz.com/edit/ngrx-data-entity-map

The technique I found was to leverage the ability to extend the `DefaultDataService` for a specific entity (I chose _Hero_ in the example below). Here's what that might look like:

```typescript
import {Injectable} from '@angular/core';
import {HttpClient} from '@angular/common/http';
import {EntityCollectionDataService, DefaultDataService, HttpUrlGenerator, QueryParams} from 'ngrx-data';
import { Observable } from 'rxjs/Observable';
import {map} from 'rxjs/operators';
import {Hero} from '../core';

@Injectable()
export class HeroEntityDataService extends DefaultDataService<Hero> {

  constructor(http: HttpClient, httpUrlGenerator: HttpUrlGenerator) {
    super('Hero', http, httpUrlGenerator);
  }

  getAll(): Observable<Hero[]> {
    return super.getAll().pipe(
      map(heroes => {
        return heroes.map(hero => this.mapHero(hero))
      })
    );
  }

  getById(id: string|number): Observable<Hero> {
    return super.getById(id).pipe(
      map(hero => this.mapHero(hero))
    );
  }

  getWithQuery(params: string | QueryParams): Observable<Hero[]> {
    return super.getWithQuery(params).pipe(
      map(heroes => {
        return heroes.map(hero => this.mapHero(hero))
      })
    );
  }

  private mapHero(hero: Hero): Hero {
    hero.mapped = 'SUCCESSFULLY MAPPED!';
    return hero;
  }
}
```

In my case I wanted to use virtually all of the goodness provided by ngrx-data so I opted to extend the `DefaultDataService<Hero>` class so I didn't need to rewrite all the other stuff. I simply wanted to run some code right after data is retrieved, so I overrode the 3 _get_ methods and added the `map` call I needed. With this class ready to do you then need to register it with ngrx-data, and that can be done in the `EntityStoreModule` like so:

```typescript
import { NgModule } from '@angular/core';
import { EntityMetadataMap, NgrxDataModule, EntityDataService } from 'ngrx-data';
import {HeroEntityDataService} from './hero-entity-data-service.service';

export const entityMetadata: EntityMetadataMap = {
  Hero: {},
  Villain: {}
};

// because the plural of "hero" is not "heros"
export const pluralNames = { Hero: 'Heroes' };

@NgModule({
  imports: [
    NgrxDataModule.forRoot({
      entityMetadata: entityMetadata,
      pluralNames: pluralNames
    })
  ],
  providers: [HeroEntityDataService]
})
export class EntityStoreModule {
  constructor(heroEntityDataService: HeroEntityDataService, entityDataService: EntityDataService) {
    entityDataService.registerService('Hero', heroEntityDataService);
  }
}
```

With this done you can use ngrx-data in your app like normal, but the server data will be updated automatically for you. 

I'd really appreciate hearing from others if this is a good approach, or from @johnpapa or @wardbell  on whether adding the example above (or something with improvements) would be a valuable addition to the docs. If not, no problem and feel free to close this.

**Comment by wardbell** [comment]
You're following the path I would recommend! That's why the `EntityDataService.registerService()` exists.

If this happens with all your entity collections, you should consider replacing the entire `DefaultDataService` with an alternative that handles serialization/deserialization for all collections.

Alternatively, you could handle these chores with an Angular `HttpInterceptor` but that's too much magic for me.

I've thought about adding a `serializer` plugin so you wouldn't have to replace the `DefaultDataService` or the collection data services for this purpose. I'm not ready to pursue that angle yet.

I'd love it if you turned this into a PR that updates the `docs/data-service.md`.

Can I persuade you? Leaving the issue open for your answer.

**Comment by sstorie** [comment]
Yeah, I'd be happy to contribute something. I'll work to create a PR this week. Thanks Ward.

**Comment by tarundhillon** [comment]
Hello - Thanks for the updating an example for overriding the DefaultDataService for a particular entity, I am wondering how to deal with a scenario where we want to replace/override DefaultDataService for all entities ? 

I am presuming I can write a similar class to DefaultDataService but not clear on how to configure it to be used by all entities ? 

Thanks
