### ISSUE TITLE
Error when tried to start server with the V6 version

### ISSUE THREAD

**Issue by israelpereira** [johnpapa/angular-ngrx-data#149]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ X ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> ng build

### Any log messages given by the failure
>
 ng build

Date: 2018-05-08T14:16:44.216Z
Hash: d1b78eb64b980593faa0
Time: 14437ms
chunk {app-heroes-heroes-module} app-heroes-heroes-module.js, app-heroes-heroes-module.js.map (app-heroes-heroes-module) 237 kB  [rendered]
chunk {app-villains-villains-module} app-villains-villains-module.js, app-villains-villains-module.js.map (app-villains-villains-module) 311 kB  [rendered]
chunk {main} main.js, main.js.map (main) 166 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 269 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 8.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 225 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 6.67 MB [initial] [rendered]

ERROR in ../app/heroes/heroes.service.ts
Module not found: Error: Can't resolve 'C:\Workspace\pessoal\frontend\angular-6\angular-ngrx-data\dist\ngrx-data' in 'C:\Workspace\pessoal\frontend\angular-6\angular-ngrx-data\src\app\heroes'
ERROR in ../app/heroes/heroes/heroes.v1.component.ts
Module not found: Error: Can't resolve 'C:\Workspace\pessoal\frontend\angular-6\angular-ngrx-data\dist\ngrx-data' in 'C:\Workspace\pessoal\frontend\angular-6\angular-ngrx-data\src\app\heroes\heroes'
ERROR in ../app/store/entity-store.module.ts
Module not found: Error: Can't resolve 'C:\Workspace\pessoal\frontend\angular-6\angular-ngrx-data\dist\ngrx-data' in 'C:\Workspace\pessoal\frontend\angular-6\angular-ngrx-data\src\app\store'
ERROR in ../app/store/app-utils.ts
Module not found: Error: Can't resolve 'C:\Workspace\pessoal\frontend\angular-6\angular-ngrx-data\dist\ngrx-data' in 'C:\Workspace\pessoal\frontend\angular-6\angular-ngrx-data\src\app\store'
ERROR in ../app/store/entity-metadata.ts
Module not found: Error: Can't resolve 'C:\Workspace\pessoal\frontend\angular-6\angular-ngrx-data\dist\ngrx-data' in 'C:\Workspace\pessoal\frontend\angular-6\angular-ngrx-data\src\app\store'
ERROR in ../app/store/ngrx-data-toast.service.ts
Module not found: Error: Can't resolve 'C:\Workspace\pessoal\frontend\angular-6\angular-ngrx-data\dist\ngrx-data' in 'C:\Workspace\pessoal\frontend\angular-6\angular-ngrx-data\src\app\store'
ERROR in ../app/villains/villains.service.ts
Module not found: Error: Can't resolve 'C:\Workspace\pessoal\frontend\angular-6\angular-ngrx-data\dist\ngrx-data' in 'C:\Workspace\pessoal\frontend\angular-6\angular-ngrx-data\src\app\villains'
ERROR in ../app/villains/villain-editor/villain-editor.component.ts
Module not found: Error: Can't resolve 'C:\Workspace\pessoal\frontend\angular-6\angular-ngrx-data\dist\ngrx-data' in 'C:\Workspace\pessoal\frontend\angular-6\angular-ngrx-data\src\app\villains\villain-editor'

### Expected/desired behavior
> server start 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows  10

### Versions
> Professional

### Mention any other details that might be useful

> I get the new V6 version and tried to start the server but i am getting those errors messages

> Thanks! We'll be in touch soon.

**Comment by israelpereira** [comment]
I found what was causing the problem..
There is a "paths" property in the tsconfig.app.json setting the ngrx path, I removed it and everything started work fine again. 

    "paths": {
      "ngrx-data": ["../dist/ngrx-data"]
    }

Thanks

**Comment by wardbell** [comment]
I don't understand the issue. I'm running `ng build` all the time. You're describing your project which should not have that `paths` property because you'll have `ngrx-data` in `node_modules`.

You closed it. Then reopened. So is the issue open or closed?

**Comment by israelpereira** [comment]
Is open.. 

These are the files that I had to removed the property paths from, locally in my project.

https://github.com/johnpapa/angular-ngrx-data/blob/master/tsconfig.json
https://github.com/johnpapa/angular-ngrx-data/blob/master/src/tsconfig.app.json

Before I remove, ng build can't resolve the ngrx in "dist\ngrx-data" path. For me is working now, but I don't know if this is the best fix.
