### ISSUE TITLE
Pessimistic deletes do not remove entity from entity collection 

### ISSUE THREAD

**Issue by philipjfulcher** [johnpapa/angular-ngrx-data#154]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Configure an Entity with all dispatcher options set to pessimistic:
```
    entityDispatcherOptions: {
      optimisticAdd: false,
      optimisticDelete: false,
      optimisticUpdate: false,
    },
```
2. Call the delete function on the entityService:
```
    this.locationsEntityService.delete(location.id);
```
3. Observe that the network request is made to delete the entity.
4. Observe that the entity still remains in the collection.

### Any log messages given by the failure
Two actions are dispatched when using the delete function on the EntityService:
```
{
  type: '[Location] ngrx-data/save/delete-one',
  entityName: 'Location',
  op: 'ngrx-data/save/delete-one',
  payload: 'b2632b51-ab9d-4e79-bf0d-9a622f31be62'
}
```

```
{
  type: '[Location] ngrx-data/save/delete-one/success',
  entityName: 'Location',
  op: 'ngrx-data/save/delete-one/success',
  payload: null
}
```

### Expected/desired behavior
On a successful delete from the server, the entity should be removed from the collection.

### OS and Version?
Windows 10

### Versions
>1.0.0-beta.9

### Mention any other details that might be useful

My assumption is that the second action listed above should have a payload containing the id of the entity.

We have also implemented a custom DataService. Our delete function there looks like this:

```
  delete(id: string): Observable<null> {
    return this.apiUrl$.pipe(exhaustMap(apiUrl => this.httpClient.delete(`${apiUrl}(${id})`)), map(response => null));
  }
```

The Observable<null> return on the interface stuck out as odd to us. It seems like it should be returning the id of the entity so that it can be dispatched as part of the success action.

Are we making any bad assumptions with our expected behavior? 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wardbell** [comment]
**You're right!**  I missed this one and didn't have a test for it.

I will do something about this tomorrow.

TBH, I'm not fond of the current protocol because it doesn't support undo for optimistic failures. So I _may_ try to address that deficiency at the same time. 

I'll let you know.

Thanks for catching this.
