### ISSUE TITLE
getAll failing silently when running with --prod

### ISSUE THREAD

**Issue by John-Bell** [johnpapa/angular-ngrx-data#156]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [x ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 
1. Create service which extends EntityCollectionServiceBase in the same way as the ngrx-data example.  
2. run without any data source, using 'ng serve'
3. 404 errors shown in console.
4. run without any data source using 'ng serve --prod'
5.  404 errors not shown

### Any log messages given by the failure
>No log messages shown

### Expected/desired behavior
>Errors displayed in console

### OS and Version?
> Windows 10.

### Versions
>6.0.0-beta.2 & 6.0.0-beta.4

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jberall** [comment]
I had the same bug.
The bug also occurs when using the ng build --prod.
It does not occur on ng serve or ng build.

**Comment by John-Bell** [comment]
It may well be more serious than logging the errors since I’m not even seeing an attempted request on the network tab.  The only reason I’m looking for the errors is it’s not getting the data when running as prod.

**Comment by wardbell** [comment]
That does not sound good :(.  I will look into this, pronto.

If you beat me too it and can find out what is wrong, a PR will be appreciated.!

**Comment by John-Bell** [comment]
I thought it was something I was doing wrong, so I’ve spent the last 2 days trying to figure it out.  I”m still trying to figure out a lot of things much as I’d like to help, sorry.

**Comment by wardbell** [comment]
I've traced it to the fact that `Actions` from  `@ngrx/effects` is NOT emitting any actions in a production build. This means that the `persist$` effect (which makes the HTTP request) is never called (as it is in a dev build).

I don't know why, what happened, when it happened.  I'm looking into it.

**Comment by wardbell** [comment]
Did it _ever_ work? I'm pretty sure it used to but I confess my tests run against dev builds and so I missed it. I'm wondering if your app used to work with a production build and suddenly stopped.

**Comment by John-Bell** [comment]
Just rechecked a copy of the heroes / villains quick start I had which is using  "ngrx-data": "^1.0.0-beta.11" and "@ngrx/effects": "^5.2.0" .  This does work using --prod in so far making a network request, failing and logging an error in the console when mock in memory database is available.

**Comment by wardbell** [comment]
I seem to have "fixed" it simply by updating the version of ng-packagr to `v3.0.0-rc.5`.  That's the build tool that produces the ngrx-data npm package.

It's all black magic in there. Once we get ngrx-data over to `@ngrx/data`, it will be on the same build platform as the rest of `@ngrx`. That should help.

Try the just release ngrx-data beta.5. It should solve this production problem.

Please let me know HERE if it does or does not.

**Comment by John-Bell** [comment]
It Works!

Tested against ng serve --prod and ng build --prod.  

Data is successfully retrieved from a .Net Core Web Api controller.

Thank you so much
