### ISSUE TITLE
Consider renaming the package

### ISSUE THREAD

**Issue by LayZeeDK** [johnpapa/angular-ngrx-data#158]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Mention any other details that might be useful

Please consider finding a more meaningful package name than `@ngrx/data`.

Suggestions:
- `@ngrx/back-end`
- `@ngrx/entity-back-end`
- `@ngrx/conventional-entities`

**Comment by wardbell** [comment]
The library will be renamed after it is moved to `@ngrx`. TBH, naming is a rat hole. Can't please everyone and rarely please more than 50%. So we'll come up with something and trust the community to accept it if it doesn't please. Closing because we're dealing with it elsewhere.

**Comment by LayZeeDK** [comment]
Thank you for your prompt reply, Ward.

I look forward to see what you come up with.
