### ISSUE TITLE
EntityMetaMap selectId function in the EntityStoreModule does not compile for production.

### ISSUE THREAD

**Issue by jberall** [johnpapa/angular-ngrx-data#160]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
The error is generated in the EntityMetaMap selectId function in the EntityStoreModule .
The ng serve works perfectly.  
The ng serve --prod  (or ng build --prod) does not compile because of ClauseAuditHistory: { selectId: selectedIdToUUID }.  (export const selectedIdToUUID = model => model.uuid;)
It does compile when I have ClauseAuditHistory: { }. 

Below is the entire EntityStoreModule 
`
import {
  ClauseTagService,
  ClauseService,
  HeroService,
  ClauseAuditHistoryService
} from './services';

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  EntityDataService,
  EntityMetadataMap,
  NgrxDataModule
} from 'ngrx-data';
import { environment } from '../../environments/environment';
// import { NgrxDataToastService } from './ngrx-data-toast.service';

// ===================Area Of BUG ===============
export const selectedIdToUUID = model => model.uuid;

export const entityMetadata: EntityMetadataMap = {
  Hero: {},
  Clause: {},
  ClauseTag: {},
  ClauseAuditHistory: { selectId: selectedIdToUUID }
};
// ================ End area of BUG ==================
// because the plural of "hero" is not "heros"
export const pluralNames = {
  Hero: 'Heroes',
  ClauseAuditHistory: 'ClauseAuditHistories'
};

@NgModule({
  imports: [
    CommonModule,
    NgrxDataModule.forRoot({
      entityMetadata: entityMetadata,
      pluralNames: pluralNames
    })
  ],
  declarations: [],
  providers: [HeroService]
})
export class EntityStoreModule {
  constructor(
    entityDataService: EntityDataService,
    heroDataService: HeroService,
    clauseService: ClauseService,
    clauseTagService: ClauseTagService,
    clauseAuditHistoryService: ClauseAuditHistoryService
  ) {
    // Register custom EntityDataServices

    entityDataService.registerService('Hero', heroDataService); // <-- register it
    entityDataService.registerServices({
      Clause: clauseService,
      ClauseTag: clauseTagService,
      ClauseAuditHistory: clauseAuditHistoryService
    });
  }
}

`

### Any log messages given by the failure
Error message when  run ng serve --prod or ng build --prod

ERROR in Error during template compile of 'EntityStoreModule'
  Function expressions are not supported in decorators in 'entityMetadata'
    'entityMetadata' references 'selectedIdToUUID'
      'selectedIdToUUID' contains the error at src\app\store\entity-store.module.ts(18,33)
        Consider changing the function expression into an exported function.
### Expected/desired behavior
expect to compile with ng serve --prod
>

### OS and Version?
> 
Windows 10 Pro version 1709

### Versions
>

Angular CLI: 6.0.0
Node: 8.11.1
OS: win32 x64
Angular: 6.0.0
    "@ngrx/effects": "^6.0.1",
    "@ngrx/entity": "^6.0.1",
    "@ngrx/router-store": "^6.0.1",
    "@ngrx/store": "^6.0.1",
    "@ngrx/store-devtools": "^6.0.1",
   "ngrx-data": "^6.0.0-beta.6",
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ColinBlair** [comment]
That is a problem with AOT compilation, not ngrx-data.

**Comment by jberall** [comment]
Colin you are correct.
The solution is to have the function as
/**
 * @returns model.uuid as the selectedId
 */
export function selectedIdToUUID(model) {
  return model.uuid;
}

When using AOT arrow functions is the problem.  It must be like above.
Thanks for the help.
