### ISSUE TITLE
introduce entities as state over observable socket connections into ngrx .

### ISSUE THREAD

**Issue by laurencefass** [johnpapa/angular-ngrx-data#161]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] feature request
```

### Expected/desired behavior
> essentially introduce entities as state over observable socket connections into ngrx .

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
any

### Versions
> latest

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wardbell** [comment]
Please tell us more about your user cases, user stories, and how you think it might work.

**Comment by wardbell** [comment]
Unlikely to get to this. Closing (for now). If you have ideas, by all means submit examples and PR
