### ISSUE TITLE
beta.8 break update webapi

### ISSUE THREAD

**Issue by rexebin** [johnpapa/angular-ngrx-data#165]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>1. custom data service extending EntityCollectionServiceBase
>1. call `update` base method with `Partial<T>`
>1. remote is called with complex object of type Update<T>: {id: string|number, changes: T}

### Any log messages given by the failure
>

### Expected/desired behavior
> as the behavior before Beta 8, the remote call's body should be entity T flat object only, which is what the dotnet core webapi expect: a full updated entity. Complex object like Update<T> is difficult to work with for webapi.

### OS and Version?
> Windows 10

### Versions
>beta.8

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rexebin** [comment]
Correction: complex object like Update is NOT difficult to work with for webapi, but to me, it is very strange and unnecessary to me. 

I have not checked the Restful spec, but if the spec specify as such, it is a bug fix rather than a bug.

**Comment by wardbell** [comment]
It should NOT send Update to a server. Should just be the entity. I will confirm your finding and fix. I wonder how it got by my tests? Maybe I wrote a bad test.

**Comment by wardbell** [comment]
Found the bug ... and how my tests missed it. Fixing. Will be fixed in Beta 9.

**Comment by rexebin** [comment]
Thanks for the fix. Is this the new ngrx-breeze in the near future?

**Comment by wardbell** [comment]
Closed by Beta 9.

>Is this the new ngrx-breeze in the near future?

LOL. It certainly is acquiring Breeze features.  It's not nearly as capable as Breeze. Not as heavy either. We'll see where the real world use cases drive us!
