### ISSUE TITLE
Question - Example on use actions.op globally? (replaced entityActions)

### ISSUE THREAD

**Issue by jberall** [johnpapa/angular-ngrx-data#171]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wardbell** [comment]
I don't know what you're asking. Please describe your need more fully, preferably with an example.

**Comment by jberall** [comment]
In the alpha system their was a way to use a 
import { NgrxDataToastService } from './ngrx-data-toast.service';

So on any operation we could trigger a notice.
Is that still possible?
Love the product.

**Comment by jberall** [comment]
I apologize.  
The answer is in the repository.
https://github.com/johnpapa/angular-ngrx-data/blob/master/src/app/store/entity/entity-store.module.ts
