### ISSUE TITLE
factory function don't work well when in production

### ISSUE THREAD

**Issue by jberall** [johnpapa/angular-ngrx-data#182]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
I have a factory function to create a service.  While in development everything works fine.
When compiled in production the entityHttpResourceUrls  overwrite the entityUrl/entitiesUrl  to the default of ngrx-data.
In development the url is http://localhost:3000/api/super-heroes and in production it turns to http://localhost:3000/api/heroes
The DefaultDataServiceConfig seems to  overwrite the entityUrl/entitiesUrl in the service.  

export const urlConfig: DefaultDataServiceConfig = {
  root:  environment.API_URL + '/api',
  timeout: 2000,
  getDelay: environment.API_URL === 'http://localhost:3000' ? 500 : 0,
  saveDelay: environment.API_URL === 'http://localhost:3000' ? 500 : 0
   entityHttpResourceUrls: {
     Villain: {
       entityResourceUrl: urlRoot + '/super-villain/',
       collectionResourceUrl: urlRoot + '/super-villains/'
      },

 }
};

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
macOS High Sierra
### Versions
> 10.13.16

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wardbell** [comment]
You are in complete control of the `DefaultDataServiceConfig` that is actually used. Create your own and provide it.

Maybe I'm missing something but I don't see what. Closing (for now). Open a new issue with more details if you haven't figured it out.

Thanks for trying ngrx-data.
