### ISSUE TITLE
Custom Mapping Response coming from EntityCollectionService.getAll()

### ISSUE THREAD

**Issue by brandondtran** [johnpapa/angular-ngrx-data#183]
Is there a way to configure EntityMetadataMap so that it stores just a single instance of an entity?  

For example, if I had a "Configuration" entity that I request from a backend service, how would I go about setting that up?

export const entityMetadata: EntityMetadataMap = {
  Configuration: {}
};

this.configurationService.getAll() ---> Return an observable with just a single Configuration object instead of an array of Configurations.

Edit:

Maybe I have to create a custom ConfigurationDataService and override getAll?

Edit 2:

Changed title of this issue.

**Comment by jberall** [comment]
If you want to return a single instance then this.configurationService.getById(id: string | number).
You should download the source and run the hero/villain.

**Comment by brandondtran** [comment]
@jberall That is assuming that my request is getting a single instance out of an array.

But what if my endpoint was just http://domain/api/bob, and that endpoint always returns a single bob object { "id": 123, "name": "bob" }?  Now getByKey won't work because I have to pass in a string | number even though that endpoint does not require an id.  And getAll won't work because getAll assumes an array is being returned by the back end.  If I try using getAll, the URL is correct, but I get an error saying "entities.reduce" is not a function because the response body is an object, not an array.

**Comment by brandondtran** [comment]
@jberall Also, what if instead of an array being returned for my collection requests, I get an object like this:

{
  "people": [{
   "id": 124,
   "name": "bob"
   }, {
   "id": 123,
   "name": "john"
   }, {
   "id": 122,
   "name": "dillon"
   }, ]
}

getAll wouldn't work...

Is there a way to custom map the response?  It seems the DefaultDataService is a bit limited in this capacity.

**Comment by brandondtran** [comment]
My final solution was to create a custom DefaultDataService for my entity and overriding getById:

`  getById(id: string | number): Observable<AppConfig> {
    return this.execute('GET', this.entityUrl);
  }`

**Comment by alekline** [comment]
Hi there! 

A newbie here, so please bare in mind my question might be missing some points. I've spent more than 10 hours trying to get this work with no luck.

Could you please provide a more basic, longer explanation on how your solution worked? I am having a hard time trying to follow up on that

I am having the exact same issue as you. My server returns an object with a list inside, like the one you mentioned above:
{
  "people": [{
   "id": 124,
   "name": "bob"
   }, {
   "id": 123,
   "name": "john"
   }, {
   "id": 122,
   "name": "dillon"
   }, ]
}

When I override the getAll() method, I get this error:
ngrx-data.js:8470 TypeError: entities.reduce is not a function
    at EntityChangeTrackerBase.push../node_modules/ngrx-data/fesm5/ngrx-data.js.EntityChangeTrackerBase.mergeServerUpserts (ngrx-data.js:5580)
    at EntityChangeTrackerBase.push../node_modules/ngrx-data/fesm5/ngrx-data.js.EntityChangeTrackerBase.mergeQueryResults (ngrx-data.js:5318)
    at EntityCollectionReducerMethods.push../node_modules/ngrx-data/fesm5/ngrx-data.js.EntityCollectionReducerMethods.queryAllSuccess (ngrx-data.js:6244)
    at entityCollectionReducer (ngrx-data.js:7911)
    at EntityCacheReducerFactory.push../node_modules/ngrx-data/fesm5/ngrx-data.js.EntityCacheReducerFactory.applyCollectionReducer (ngrx-data.js:8402)
    at EntityCacheReducerFactory.entityCacheReducer (ngrx-data.js:8117)
    at store.js:144
    at combination (store.js:102)
    at computeNextEntry (store-devtools.js:322)
    at recomputeStates (store-devtools.js:353)

I know I have to somehow unpack the object that is inside my observable. I can see the object content if I subscribe to the observable, but I have tried many other ways of getting the data out in the Store with no luck.

Thank you!

**Comment by alekline** [comment]
Ok, so basically, the issue was that I got a Promise wrapped in an observable by using of(promise_returned_from_http_client). Instead, you should use Observable.fromPromise(promise_returned_from_http_client)
