### ISSUE TITLE
How to add custom effects for actions?

### ISSUE THREAD

**Issue by brandondtran** [johnpapa/angular-ngrx-data#186]
In the example application, NgrxDataToastService was created to intercept completed actions and show a toast for success or error.

Is that how custom effects are done in ngrx-data or is there another way?

**Comment by wardbell** [comment]
Not really. Take a look at `EntityEffects` (or the `EntityCacheEffects` that is new in v6.1.0).

You can create your own effects using straight @ngrx.

You can replace the ngrx-data effects by many means including creating your own substitute effects class and using an Angular dependency injection override-provider to replace the ngrx-data version with your own.

HTH.

I don't see an action item here, so I'm closing this issue. Thanks for your interest in ngrx-data.
