### ISSUE TITLE
Ability to add custom authentication headers

### ISSUE THREAD

**Issue by kichnan** [johnpapa/angular-ngrx-data#190]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Feature request description
Need a way to set/pass authentication headers into the underlying `HttpClient` service (used by `DefaultDataService`). I assume that most data service API calls would need some kind of authentication mechanism. Hence.

### Reason for feature request
Currently, I could not find/think of a way to achieve authentication in my app using ngrx-data alone, unless I write my own `CustomDataService` and then write the same functions (`getAll`, `getByKey`, etc.) again with _my_ implementation. That, I think, is duplicated effort. I find `DefaultDataService` really has **everything one needs** - its available functions and configurations - for pure REST calls. So, plugging just the authentication mechanism into it makes sense to me.

In any case, authentication \(headers) seems like an independent part of the data service, regardless of what one uses actually - _default_ vs. _custom_. Meaning, the same authentication configuration (injected as a dependency) could be useful in either types of services.

### Implementation
One of the ideas to implement this is to:
1. Create a new configuration class `DefaultDataAuthenticationConfig`.
    ```typescript
    export declare abstract class DefaultDataAuthenticationConfig {
        /** enum/string of values: jwt, custom. */
        type: string;
        /** enum/string of values: localStorage, sessionStorage, store, customProvider, cookie (client-side). */
        storageType: string;
        /** Array of `keys` to be fetched from `storageType`, OR array of {storageKey,headerKey} for custom headers. */
        keys?: [string | {storageKey: string; headerKey: string; }];
        /**
         * (Optional) directly pass authentication token(s) as a key-value pair.
         * Useful when you want to write your own `providers` for `DefaultDataAuthenticationConfig`.
         */
        headers?: [{key: string; value: string; }];
    }
    ```
1. Create a property in `DefaultDataServiceConfig { ..., authentication: DefaultDataAuthenticationConfig; }`. OR, keep it as an independent configuration provided separately to `DefaultDataAuthenticationService` (below).
1. Create a `DefaultDataAuthenticationService` that helps generate the required `HttpHeaders` based on the selected `storageType`, and inject this service into `EntityCollectionServiceBase`.
1. Change `EntityCollectionServiceBase.execute` to add `HttpHeaders` if available.

### Implementation questions
1. Is it advisable to add a dependency of `@ngrx/store` in `EntityCollectionServiceBase`?
1. Is it advisable to use `localStorage`, `sessionStorage`, etc. in `EntityCollectionServiceBase`?

### Mention any other details that might be useful
If feasible, I would also love to contribute to the project.

Thoughts?

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wardbell** [comment]
The ngrx-data default data service injects Angular's `HttpClient` which is the right place to intercept requests and add headers.

It's easy. Just follow the [Angular documentation on interceptors](https://angular.io/guide/http#intercepting-requests-and-responses).
