### ISSUE TITLE
Use plural style URLs for all verbs

### ISSUE THREAD

**Issue by williamBurgeson** [johnpapa/angular-ngrx-data#197]
I have been integrating the ngrx-data with a solution I am currently building, and the first step was to get all items: the entity is called Channel, and the url was "api/channels": great.

However when I try to add an entity the url requested is "api/channel".

I am using a .net core back end and therefore the controller has a single base route, and I am now forced to set routes on all actions.

I understand that this is a front end solution not intended for a specific back end, but is there a way we can easily (or by default) ensure the basic URL for all verbs is the same?

**Comment by EricPolman** [comment]
I don't think there is an actual solution, but you can work around this by naming the entity "channels" and providing a plural name "channels" so all endpoints are forced to /api/channels

**Comment by roldengarm** [comment]
Hi @williamBurgeson I had exactly the same problem. I have fixed this by providing a custom httpUrlGenerator to override this behavior.
Create a custom class `StoreHttpUrlGenerator`, override DefaultHttpUrlGenerator and provide it in your module
`{ provide: DefaultHttpUrlGenerator, useClass: StoreHttpUrlGenerator },`

Implement this method:

```
 protected getResourceUrls(
    entityName: string,
    root: string
  ): HttpResourceUrls {
    let resourceUrls = this.knownHttpResourceUrls[entityName];
    if (!resourceUrls) {
      const entityPlural = ${this.pluralizer.pluralize(
          entityName
        );
      const nRoot = normalizeRoot(root);
      resourceUrls = {
        entityResourceUrl: `${nRoot}/${entityPlural }/`.toLowerCase(),
        collectionResourceUrl: `${nRoot}/${entityPlural}/`.toLowerCase()
      };
      this.registerHttpResourceUrls({ [entityName]: resourceUrls });
    }
    return resourceUrls;
  }
```

**Comment by williamBurgeson** [comment]
Hello,

thanks for this - it might be worth putting it on the thread.

It feels a bit involved for what should be a simple setting, however I may
well look at this and put it in the work I am doing as a workaround.

For what it's worth, I would prefer not to have to write too much code to
achieve this: the entire point of using ngrx-data for me was to avoid all
the boilerplate of vanilla ngrx, at the same time being able to deviate
from the convention when appropriate, and even then hopefully this can be
done with settings rather than imperative coding, where possible.

But I think it would be valuable for other users to see the code you have
put up.

In any case, thanks for taking the time to share with me,

William

**Comment by wardbell** [comment]
The suggestion from @roldengarm - replace the `DefaultHttpUrlGenerator` as he explains above - is what I would recommend as well and happens to be what we are doing in one of our applications that also uses a single, collection name for all REST calls. Works great.

Closing because there is no obvious action item.

**Comment by jvitor83** [comment]
At module file:

```typescript
const apiRoot = 'https://some.api.com';
const defaultDataServiceConfig: DefaultDataServiceConfig = {
  root: apiRoot,
  entityHttpResourceUrls: {
    MyEntity: (<HttpResourceUrls>{ entityResourceUrl: apiRoot + '/entities', collectionResourceUrl: apiRoot + '/entities' }),
  }
};
```

Register this provider:
```typescript
    { provide: DefaultDataServiceConfig, useValue: defaultDataServiceConfig },
```

Works for me!

**Comment by ShaneK** [comment]
Just an update to this, to get this to work I had to use:

```{
	provide: HttpUrlGenerator,
	useClass: StoreHttpUrlGenerator
}```

Instead of 

```{ 
	provide: DefaultHttpUrlGenerator,
	useClass: StoreHttpUrlGenerator
}```
