### ISSUE TITLE
Allow entity to be added to the start of a collection. 

### ISSUE THREAD

**Issue by jgutix** [johnpapa/angular-ngrx-data#198]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>By using the method `addOneToCache` entities are always added to the end of a collection, however there are use cases (see one use case below) where is desirable to have the entity added at the start of a collection and therefore be presented on top of a list.

### Any log messages given by the failure
>

### Expected/desired behavior
>A parameter is added to `addOneToCache` and similar methods that will allow me to add an entity at the start of the current collection

### OS and Version?
> 

### Versions
>6.1.0-alpha.4

### Mention any other details that might be useful
Use Case:
I'm filling a table(mat-table) with data coming already desc sorted from remote. When the user adds a new entity it's expected that the new row is added at the top of the table.
If you wonder why I'm accessing `addOneToCache` directly, that's because I'm using a non-crud endpoint that returns me a newly created entity.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by philipjfulcher** [comment]
Does the endpoint return the field that is sorted descending? You could add a sortComparer to the entity metadata to handle this: https://github.com/johnpapa/angular-ngrx-data/blob/master/docs/entity-metadata.md#sortcomparer

**Comment by jgutix** [comment]
Thanks @philipjfulcher . I had looked into that, however I'm allowing some columns in the table to be sortable, and as it's now, I can't see a way to dynamically pass the field name to the sortComparer function

**Comment by wardbell** [comment]
You can't dynamically sort. The speed of the sort depends on an unchanging sort order. Dynamic sort within the collection would be too inefficient.

If you need dynamic sort, it is almost certainly for presentation. That kind of thing belongs in the UI, not in the store.

Closing because not likely to pursue this.

If you think it should remain open, please create another issue, refer to this one, and explain why.

Thanks for using ngrx-data.
