### ISSUE TITLE
Upsert triggers a create action rather than upsert

### ISSUE THREAD

**Issue by onedotover** [johnpapa/angular-ngrx-data#201]
Version: 6.1.0-beta.2

Calling EntityCollectionServiceBase.upsert() triggers a save/add-one action rather than a save/upsert-one action. I believe the problem is here:

https://github.com/johnpapa/angular-ngrx-data/blob/390d3efafce5bedb3131f88dec4f9d8ada019d7f/lib/src/dispatchers/entity-dispatcher-base.ts#L306-L309

Line 308 should be replaced with:
`const action = this.createEntityAction(EntityOp.SAVE_UPSERT_ONE, entity, options);`

**Comment by wardbell** [comment]
Great catch. Fixed in beta.3
