### ISSUE TITLE
ngrx-data roadmap

### ISSUE THREAD

**Issue by DustinJackson** [johnpapa/angular-ngrx-data#203]
Quick question

7 Months ago during the [Reducing the Boilerplate with NgRx](https://www.youtube.com/watch?v=t3jx0EC-Y3c) talk @wardbell mentioned joining the NgRx team.  Is this extension still being actively supported and will it be merged with the NgRx project at some point?

@johnpapa

**Comment by johnpapa** [comment]
Yes this is actively being worked on by @wardbell and Mike Ryan

Timeline has slowed due to trying to get it integrated with Bazel build system.

**Comment by rernens** [comment]
@wardbell @johnpapa  

Hi

Can we get some idea on when a ngrx-data version compatible with ngrx v7 can be expected.
