### ISSUE TITLE
Angular V7 and ngrx v7 support

### ISSUE THREAD

**Issue by rernens** [johnpapa/angular-ngrx-data#207]
I have been using ngrx for a while in various projects and I am at the point of starting a totally new project in which I was planning to use ngrx-data.

But as far as I can tell, ngrx-data is not yet compatible neither with Angular 7 nor with ngrx v7 which is required to work with Angular 7.

Can we get some hint on when a version of ngrx-data will be compatible with  Angular V7 and ngrx v 7 ?

Thanks

**Comment by jberall** [comment]
+1

**Comment by fergalmoran** [comment]
I'm using it heavily in a project with Angular 7.1.0 - I'm not seeing any issues?
ngrx 7 is still in beta so I haven't tried that.

**Comment by johnpapa** [comment]
@wardbell - do you have an update on ngrx 7 compat?

**Comment by enricosecondulfo** [comment]
Hello guys, any news on this? Thank you

**Comment by SerkanSipahi** [comment]
@enricosecondulfo this is the last update about ngrx-data
https://twitter.com/Bitcollage/status/1100422923406503941 follow then the github link.

**Comment by enricosecondulfo** [comment]
@SerkanSipahi thank you for your reply

**Comment by mfrieling** [comment]
I'm using Angular 7.2.0 and thinking about using ngrx-data, but when installing it I get those warnings:

```
warning " > ngrx-data@6.1.0-beta.3" has incorrect peer dependency "@ngrx/effects@^6.0.0".
warning " > ngrx-data@6.1.0-beta.3" has unmet peer dependency "@ngrx/entity@^6.0.0".
warning " > ngrx-data@6.1.0-beta.3" has incorrect peer dependency "@ngrx/store@^6.0.0".
```
- Do I have to expect any trouble from those warnings?
- How long will it probably take after the release of Angular 8 until [#1554](https://github.com/ngrx/platform/issues/1554) will be solved and ngrx-data 8 be released?

**Comment by jberall** [comment]
I have been using ngrx-data for months with ng7.2.1 with those messages and I have not had any issues.
I look forward to the upgrade and integration of ngrx.

**Comment by timdeschryver** [comment]
The `ngrx-data` has been migrated into the `ngrx` platform.
In the next version of NgRx (v8) it will become available via `@ngrx/platform`, it's currently available in the beta release.

**Comment by johnpapa** [comment]
Exactly. I’ll be closing this repo out soon and updating the readme with instructions on how to shift to the new location
