### ISSUE TITLE
Ngrx-data vs ngrx/entities

### ISSUE THREAD

**Issue by bkooistra** [johnpapa/angular-ngrx-data#208]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
### Question
Hi John,

I am reading a lot about ngrx and the need to reduce boilerplate code and manage collections of entities. To my understanding, which isn't all that much (yet), I see both ngrx/entities and ngrx-data try to solve this elegantly. I have trouble choosing or comprehending the whole mix of both.

Can you elaborate on the differences, similarities and relation between them? 

I also read that ngrx-data might become official part of ngrx/platform. Which would contradict my view that they are just two libraries trying to solve the same puzzle.

Thanks

**Comment by jberall** [comment]
If you read the documentation you'll see that ngrx-data reduces the CRUD (https://github.com/johnpapa/angular-ngrx-data).
In ngrx/entities ( https://medium.com/ngrx/introducing-ngrx-entity-598176456e15) you still have to create your own action, reducer, selector, effect, or HTTP dataservice.

**Comment by bkooistra** [comment]
Hey jberall, thanks for your answer and accompanying links. I also noticed that ngrx-data uses ngrx-effects and extends ngrx to effectively reduce boilerplate even more. I think it's safe to say I can close this issue.
