### ISSUE TITLE
Should we create collection if it does not exist?

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/angular-ngrx-data#31]
const collection = state[entityTypeName];
  // TODO: consider creating a collection if none exists.
  //       Worried now that later implementation would depend upon
  //       missing collection metadata.
  if (!collection) {
    throw new Error(`No cached collection named "${entityTypeName}")`);
  }

**Comment by wardbell** [comment]
Done. The library creates a collection on the fly when you start to access it.
