### ISSUE TITLE
document how to maintain the code styles - like prettier

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/angular-ngrx-data#35]
function pretty {
  prettier --write --print-width 100 --single-quote --tab-width 2 './src/**/*.js' './src/**/*.ts' './src/**/*.css'  !'./src/**/*.min.*'
}

**Comment by lester-joshua** [comment]
have you considered using pre-commit hooks to ensure that code styles are used?

**Comment by johnpapa** [comment]
Yes. I love prettier. And I . would love a PR for it in this repo :)


John Papa | @john_papa | JohnPapa.net, LLC

**Comment by johnpapa** [comment]
I added it to the quickstart repo. Thoughts on this?

```
  "pre-commit": "ng lint --fix --force && pretty-quick && git add .",
```

I installed `husky`, `pretty-quick`, and `prettier`. pretty quick is nice because it formats all changed files by default. lint-staged is nice, but only works on staged files.

**Comment by lester-joshua** [comment]
if it works the way you want it to for your repo then great.   honestly ive just started playing around with the precommit hook stuff and ive learn theres several ways of going about it. i almost have a PR together for this repo but it only does the staged files that are inside of the `src` folder

**Comment by johnpapa** [comment]
staged files work ... and maybe that is faster. i often commit all open changes, and they arent staged. 

interesting tho ... need to tinker and see what is the nicer workflow

**Comment by johnpapa** [comment]
so here is another option

```
    "pre-commit": "lint-staged"
  },
  "pre-commit": ["pre-commit"],
  "lint-staged": {
    "*.{ts,js,json,css,md}": ["prettier --write", "git add"]
  },
```

**Comment by johnpapa** [comment]
Merged. Closed. Thanks.
