### ISSUE TITLE
Support guid id

### ISSUE THREAD

**Issue by wardbell** [johnpapa/angular-ngrx-data#75]

**Comment by wardbell** [comment]
This is something the developer can do independently of ngrx-data. Write your own `selectId` to access it.

**Comment by jberall** [comment]
How to implement selectId.
In the EntityStoreModule define as ...
`
export const entityMetadata: EntityMetadataMap = {
  Hero: {},
  Villain: { selectId: model => model.uuid}
};
`

Other options include
export interface EntityMetadata<T = any, S extends object = {}> {
    entityName: string;
    entityDispatcherOptions?: Partial<EntityDispatcherOptions>;
    filterFn?: EntityFilterFn<T>;
    selectId?: IdSelector<T>;
    sortComparer?: false | Comparer<T>;
    additionalCollectionState?: S;
}
