### ISSUE TITLE
Compilation error in entity.actions.ts when filters are imported

### ISSUE THREAD

**Issue by ColinBlair** [johnpapa/angular-ngrx-data#97]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Add import 'rxjs/add/operator/filter'; to any component

### Any log messages given by the failure
>src/client/ngrx-data/entity.actions.ts(83,14): error TS2415: Class 'EntityActions<V>' incorrectly extends base class 'Observable<EntityAction<V, any>>'.
  Types of property 'filter' are incompatible.
    Type '<T>(predicate: (ea: EntityAction<T, any>) => boolean) => any' is not assignable to type '{ <T, S extends T>(this: Observable<T>, predicate: (value: T, index: number) => value is S, thisA...'.
      Types of parameters 'predicate' and 'predicate' are incompatible.
        Type '(value: any, index: number) => value is any' is not assignable to type '(ea: EntityAction<any, any>) => boolean'.
src/client/ngrx-data/entity.actions.ts(99,3): error TS2425: Class 'Observable<EntityAction<V, any>>' defines instance member property 'filter', but extended class 'EntityActions<V>' defines it as instance member function.
src/client/ngrx-data/entity.actions.ts(99,3): error TS7023: 'filter' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.
src/client/ngrx-data/entity.actions.ts(100,30): error TS2345: Argument of type 'this' is not assignable to parameter of type 'Observable<EntityAction<T, any>>'.
  Type 'EntityActions<V>' is not assignable to type 'Observable<EntityAction<T, any>>'.
    Types of property 'filter' are incompatible.
      Type '<T>(predicate: (ea: EntityAction<T, any>) => boolean) => any' is not assignable to type '{ <T, S extends T>(this: Observable<T>, predicate: (value: T, index: number) => value is S, thisA...'.
        Types of parameters 'predicate' and 'predicate' are incompatible.
          Type '(value: any, index: number) => value is any' is not assignable to type '(ea: EntityAction<any, any>) => boolean'.
src/client/ngrx-data/entity.actions.ts(105,5): error TS2322: Type 'this' is not assignable to type 'Observable<any>'.
  Type 'EntityActions<V>' is not assignable to type 'Observable<any>'.
    Types of property 'filter' are incompatible.
      Type '<T>(predicate: (ea: EntityAction<T, any>) => boolean) => any' is not assignable to type '{ <T, S extends T>(this: Observable<T>, predicate: (value: T, index: number) => value is S, thisA...'.
src/client/ngrx-data/entity.actions.ts(194,49): error TS2345: Argument of type 'this' is not assignable to parameter of type 'Observable<EntityAction<T, any>>'.
  Type 'EntityActions<V>' is not assignable to type 'Observable<EntityAction<T, any>>'.

### Expected/desired behavior
>Compilation without error

### OS and Version?
>Windows 7

### Versions
>Current repository

### Mention any other details that might be useful
This is looking really good so far, and just in time for me needing it. Not sure if this is a real problem, but wanted to surface it early.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wardbell** [comment]
Without an example of what you're doing I'm not sure if it is a problem with the library, if it was a problem now fixed, or if it is still a problem that I can fix.

The library has evolved rapidly since you dropped by. We're minutes away from having an npm package you can try on your own app.

Please give me a little more to work with or close this when you get a chance.

**Comment by ColinBlair** [comment]
Confirmed, the original problem is no longer happening.

**Comment by ColinBlair** [comment]
Not sure why I got a negative result last week, but the error is reproducing for me again.

Steps for reproducing:
1) Clone angular-ngrx-data
2) npm install
3) npm run build-setup
4) ng build
5) Result: Everything works fine
6) Edit heroes.component.ts to add
 import 'rxjs/add/operator/filter';
7) ng build
8) Result;
ERROR in dist/ngrx-data/entity.actions.d.ts(66,22): error TS2415: Class 'EntityActions<V>' incorrectly extends base class 'Observable<V>'.
  Types of property 'filter' are incompatible.
    Type '(predicate: (ea: EntityAction<any>) => boolean) => EntityActions<EntityAction<any>>' is not assignable to type '{ <T, S extends T>(this: Observable<T>, predicate: (value: T, index: number) => value is S, thisA...'.
      Types of parameters 'predicate' and 'predicate' are incompatible.
        Type '(value: any, index: number) => value is any' is not assignable to type '(ea: EntityAction<any>) => boolean'.
dist/ngrx-data/entity.actions.d.ts(74,5): error TS2425: Class 'Observable<V>' defines instance member property 'filter', but extended class 'EntityActions<V>' defines it as instance member function.


I have an existing Angular application template (coreui.io) that I am trying to use and the combination of CoreUI and ngrx-data is having the above error. Were you trying to override the filter method already supplied by rxjs or is this just a name collision?

**Comment by wardbell** [comment]
Good catch!  I have only been using "pipe operator" style so never considered that `EntityActions.filter()` collided with `import 'rxjs/add/operator/filter';`.

Fixing by renaming to `where()`. There is no `import { where } from 'rxjs/add/operator/where';
` to worry about.
